In [1]:
s = "Hi there Sam!"

In [2]:
s=s.split(" ")
print(s)

['Hi', 'there', 'Sam!']


In [3]:
planet = "Earth"
diameter = 12742

In [4]:
print("The diameter of {0} is {1} kilometers.".format(planet,diameter))

The diameter of Earth is 12742 kilometers.


In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

In [7]:
import numpy as np

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [10]:
print(np.arange(20,36,2))

[20 22 24 26 28 30 32 34]


In [11]:
x=np.arange(0,9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 5, 6])

In [14]:
import pandas as pd

In [15]:
v=[[41,'kavi'],[42,'pavi'],[43,'Sri']]
df=pd.DataFrame(v,columns=['ID','Name'])
df

ID  Name
0  41  kavi
1  42  pavi
2  43   Sri

In [16]:
from datetime import date,timedelta
sdate=date(2023,1,1)
edate=date(2023,2,10)
d=edate-sdate
for i in range(d.days+1):
    day=sdate+timedelta(days=i)
    print(day)

2023-01-01
2023-01-02
2023-01-03
2023-01-04
2023-01-05
2023-01-06
2023-01-07
2023-01-08
2023-01-09
2023-01-10
2023-01-11
2023-01-12
2023-01-13
2023-01-14
2023-01-15
2023-01-16
2023-01-17
2023-01-18
2023-01-19
2023-01-20
2023-01-21
2023-01-22
2023-01-23
2023-01-24
2023-01-25
2023-01-26
2023-01-27
2023-01-28
2023-01-29
2023-01-30
2023-01-31
2023-02-01
2023-02-02
2023-02-03
2023-02-04
2023-02-05
2023-02-06
2023-02-07
2023-02-08
2023-02-09
2023-02-10


In [17]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [18]:
df1=pd.DataFrame(lists)
df1

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24